//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wshare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Article
    {
        public T_Article()
        {
            this.T_Comment = new HashSet<T_Comment>();
            this.T_Visitors = new HashSet<T_Visitors>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string Tags { get; set; }
        public string Author { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
        public int Visitors { get; set; }
        public int Reading { get; set; }
        public string Cover { get; set; }
        public string Source { get; set; }
        public string Contents { get; set; }
        public int State { get; set; }
    
        public virtual ICollection<T_Comment> T_Comment { get; set; }
        public virtual ICollection<T_Visitors> T_Visitors { get; set; }
    }
}
