//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wshare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_User
    {
        public T_User()
        {
            this.T_Agree = new HashSet<T_Agree>();
            this.T_Authorize = new HashSet<T_Authorize>();
            this.T_Comment = new HashSet<T_Comment>();
            this.T_Visitors = new HashSet<T_Visitors>();
            this.T_Visitors1 = new HashSet<T_Visitors>();
            this.T_Pay = new HashSet<T_Pay>();
            this.T_TiXian = new HashSet<T_TiXian>();
        }
    
        public int Id { get; set; }
        public string Openid { get; set; }
        public string Nickname { get; set; }
        public string Sex { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Headimgurl { get; set; }
        public string Unionid { get; set; }
        public System.DateTime CreateTime { get; set; }
        public bool IsEnable { get; set; }
        public int Score { get; set; }
        public string PayRemark { get; set; }
    
        public virtual ICollection<T_Agree> T_Agree { get; set; }
        public virtual ICollection<T_Authorize> T_Authorize { get; set; }
        public virtual ICollection<T_Comment> T_Comment { get; set; }
        public virtual ICollection<T_Visitors> T_Visitors { get; set; }
        public virtual ICollection<T_Visitors> T_Visitors1 { get; set; }
        public virtual ICollection<T_Pay> T_Pay { get; set; }
        public virtual ICollection<T_TiXian> T_TiXian { get; set; }
    }
}
