//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wshare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Visitors
    {
        public int Id { get; set; }
        public int ArticleId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ShareId { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual T_Article T_Article { get; set; }
        public virtual T_User T_User { get; set; }
        public virtual T_User T_User1 { get; set; }
    }
}
