//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wshare.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class wshareEntities : DbContext
    {
        public wshareEntities()
            : base("name=wshareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T_Agree> T_Agree { get; set; }
        public DbSet<T_Article> T_Article { get; set; }
        public DbSet<T_Authorize> T_Authorize { get; set; }
        public DbSet<T_Comment> T_Comment { get; set; }
        public DbSet<T_User> T_User { get; set; }
        public DbSet<T_Visitors> T_Visitors { get; set; }
        public DbSet<T_Admin> T_Admin { get; set; }
        public DbSet<T_Tags> T_Tags { get; set; }
        public DbSet<T_Files> T_Files { get; set; }
        public DbSet<T_Pay> T_Pay { get; set; }
    }
}
